[package]
name = "gui-is-a-sin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#iced = "0.3"
terminal-menu = "*"
crossterm = "0.20.0"
nixinfo = "0.3.3"