[package]
name = "damo_fetch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nixinfo = "0.2.8"
nixinfo = { git = "https://github.com/Dam-0/nixinfo" }