[package]
name = "starter_programs"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "guess_game"
path = "src/guess_game.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"