[package]
name = "starter_programs"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mem_loop"
path = "src/mem_loop.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"