[package]
name = "starter_programs"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "todo_list"
path = "src/todo_list.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
